package edu.wz.cs.leetcode.easy;

/**
 * 389. Find the Difference<br>
 * https://leetcode.com/problems/find-the-difference<br><br>
 * 
 * Given two strings s and t which consist of only lowercase letters. String t is generated by random shuffling string s
 * and then add one more letter at a random position. Find the letter that was added in t.
 */
public class FindDifference {

    public static char solution(String s, String t) {        
        int[] freq = new int[26];
        
        for (char c : s.toCharArray()) {
            freq[c - 'a']++;
        }
        
        for (char c : t.toCharArray()) {
            freq[c - 'a']--;
            if (freq[c - 'a'] < 0) {
                return c;
            }
        }
        
        return ' ';
    }
    
    public static char solutionX(String s, String t) {
        int result = 0;
        for (char c : t.toCharArray()) {
            result += c;
        }
        for (char c : s.toCharArray()) {
            result -= c;
        }
        return (char) result;
    }
    
    public static void main(String[] args) {
        System.out.println(FindDifference.solution("abcd", "abcde"));
        System.out.println(FindDifference.solutionX("abcd", "abcde"));
    }

}
